output_dir: /home/icb/yue.hu/proj_genefun/AStarNet/

dataset:
  class: biomedical
  path: /home/icb/yue.hu/proj_genefun/NBFNet/data/primekg/disease_split/anemia_42
  include_factgraph: True

task:
  class: KnowledgeGraphCompletionBiomed
  model:
    class: AStarNet
    base_layer:
      class: NBFNetConv
      input_dim: 32
      output_dim: 32
      query_input_dim: 32
      message_func: distmult
      aggregate_func: pna
      layer_norm: yes
      dependent: yes
    num_layer: 4
    short_cut: yes
    remove_one_hop: yes
    node_ratio: 1
  criterion: bce
  num_negative: 32
  strict_negative: yes
  heterogeneous_negative: yes
  heterogeneous_evaluation: yes
  adversarial_temperature: 0.9
  sample_weight: no
  full_batch_eval: yes
  conditional_probability: yes

optimizer:
  class: Adam
  lr: 5.0e-3

engine:
  gpus: {{ gpus }}
  batch_size: 4

train:
  num_epoch: 1
  batch_per_epoch: 1000

metric: mrr
