output_dir: experiments

dataset:
  class: biomedical
  path: data/random_42
  include_factgraph: True


task:
  class: KnowledgeGraphCompletionBiomed
  model:
    class: AStarNet
    base_layer:
      class: NBFNetConv
      input_dim: 32
      output_dim: 32
      query_input_dim: 32
      message_func: distmult
      aggregate_func: pna
      layer_norm: yes
      dependent: no
    num_layer: 4
    short_cut: no
    remove_one_hop: yes
    node_ratio: 0.5
  criterion: bce
  num_negative: 32
  strict_negative: yes
  heterogeneous_negative: yes
  heterogeneous_evaluation: yes
  adversarial_temperature: 0.9
  sample_weight: no
  full_batch_eval: yes
  conditional_probability: yes
  train2_in_factgraph: no

optimizer:
  class: Adam
  lr: 5.0e-5

engine:
  gpus: {{ gpus }}
  batch_size: 16
  log_interval: 10
  gradient_interval: 4

train:
  num_epoch: 4
  batch_per_epoch: 1000

metric: mrr
